import {
  FacebookShareButton,
  LinkedinShareButton,
  TwitterShareButton,
  PinterestShareButton,
  VKShareButton,
  OKShareButton,
  TelegramShareButton,
  WhatsappShareButton,
  RedditShareButton,
  EmailShareButton,
  TumblrShareButton,
  LivejournalShareButton,
  MailruShareButton,
  ViberShareButton,
  WorkplaceShareButton,
  LineShareButton,
  WeiboShareButton,
  PocketShareButton,
  InstapaperShareButton,
  FacebookIcon,
  TwitterIcon,
  LinkedinIcon,
  PinterestIcon,
  VKIcon,
  OKIcon,
  TelegramIcon,
  WhatsappIcon,
  RedditIcon,
  TumblrIcon,
  MailruIcon,
  EmailIcon,
  LivejournalIcon,
  ViberIcon,
  WorkplaceIcon,
  LineIcon,
  PocketIcon,
  InstapaperIcon,
} from "react-share";

export default [
  {
    id: "facebook",
    Component: FacebookShareButton,
    Icon: FacebookIcon,
  },
  {
    id: "linkedin",
    Component: LinkedinShareButton,
    Icon: LinkedinIcon,
  },
  {
    id: "twitter",
    Component: TwitterShareButton,
    Icon: TwitterIcon,
  },
  {
    id: "pinterest",
    Component: PinterestShareButton,
    Icon: PinterestIcon,
  },
  {
    id: "email",
    Component: EmailShareButton,
    Icon: EmailIcon,
  },
  {
    id: "reddit",
    Component: RedditShareButton,
    Icon: RedditIcon,
  },
  {
    id: "whatsapp",
    Component: WhatsappShareButton,
    Icon: WhatsappIcon,
  },
  {
    id: "pocket",
    Component: PocketShareButton,
    Icon: PocketIcon,
  },
  {
    id: "instapaper",
    Component: InstapaperShareButton,
    Icon: InstapaperIcon,
  },
  {
    id: "tumblr",
    Component: TumblrShareButton,
    Icon: TumblrIcon,
  },
  // {
  //   id: "line",
  //   Component: LineShareButton,
  //   Icon: LineIcon,
  // },
  // {
  //   id: "viber",
  //   Component: ViberShareButton,
  //   Icon: ViberIcon,
  // },
  // {
  //   id: "livejournal",
  //   Component: LivejournalShareButton,
  //   Icon: LivejournalIcon,
  // },
  // {
  //   id: "vk",
  //   Component: VKShareButton,
  //   Icon: VKIcon,
  // },
  // {
  //   id: "ok",
  //   Component: OKShareButton,
  //   Icon: OKIcon,
  // },
  // {
  //   id: "mailru",
  //   Component: MailruShareButton,
  //   Icon: MailruIcon,
  // },
  // {
  //   id: "workplace",
  //   Component: WorkplaceShareButton,
  //   Icon: WorkplaceIcon,
  // },
];
